### ISSUE TITLE
Contribute to upstream?

### ISSUE THREAD

**Issue by VojtechVitek** [Kiho/use-svelte-store#1]
Hi,

I noticed this is a fork of @Crisfole https://github.com/Crisfole/react-use-svelte-store, which removes `svelte` as a required NPM (dev) dependency. Have you considered contributing these changes to the upstream repository?

Thanks,
Vojtech

**Comment by Crisfole** [comment]
Also, since svelte is a _dev_ dependency it should only install when you're working on it locally (run `npm install` from inside this repo). Installing it in another package (`npm install use-svelte-store`) should _not_ include svelte as a dep except whatever parts are re-exported.

**Comment by Crisfole** [comment]
If you don't want the re-export simply don't import it and use a tree-shaking bundler to rid yourselves of my unwanted helper exports. ;)

**Comment by Kiho** [comment]
I am trying to use this code in library, I really don't want that anybody using my lib bothered by installing svelte on react application they build. anyway if @Crisfole want this in then I have no problem with making PR.

**Comment by Kiho** [comment]
Since svelte peer dependency is removed from upstream, I don't think we need PR here.

**Comment by VojtechVitek** [comment]
Thanks both! Svelte Stores are amazingly simple and I'm glad you brought them over to React 👍

**Comment by Crisfole** [comment]
My pleasure! Either of you are welcome to ping me directly on Discord (I'm in the Svelte channels somewhat regularly) if something doesn't work as expected.
